# Generated by Django 6.1 on 2026-09-06 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='child',
            name='program',
            field=models.CharField(blank=True, choices=[('quran', "Qur'an"), ('youth_program', 'Youth Program'), ('islamic_studies', 'Islamic Studies')], max_length=20, null=True),
        ),
    ]
