# Generated by Django 6.0.5 on 2026-09-06 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_child_program'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_type',
            field=models.CharField(choices=[('0', 'Youth Group'), ('1', 'Hifz'), ('2', 'Islamic Studies')], max_length=10),
        ),
    ]
